vim.g.mapleader = " "
local opt = vim.opt
opt.guicursor = ""
opt.clipboard = "unnamedplus"
opt.modelines = 0
opt.maxmempattern = 2500
opt.number = true
opt.relativenumber = true
opt.wrap = true
opt.cursorline = true
opt.breakindent = true
opt.linebreak = true
opt.signcolumn = "yes"
opt.colorcolumn = "80"
opt.scrolloff = 8
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.shiftround = true
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = false
opt.laststatus = 3
opt.lazyredraw = true
opt.splitright = true
opt.completeopt = { "menu", "menuone", "noselect" }
opt.title = true
